version: '3.8'

services:
  django:
    build:
      context: ./backend
    container_name: django-app
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "backend.wsgi:application"]
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: nextjs-app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - django

  db:
    image: postgres:14
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    ports:
      - "5432:5432"

volumes:
  postgres_data:
